### ISSUE TITLE
TableGen.cpp:244:37: error: too few arguments to function call

### ISSUE THREAD

**Issue by Crazor** [avr-llvm/clang#11]
I'm compiling avr-llvm (06faf0a) as per the wiki, with clang (ee44fb6) checked out into the tools/ folder. I'm compiling on OS X 10.11.6 with Xcode 7.3.1. make stops with the following message:

> [ 67%] Building CXX object tools/clang/utils/TableGen/CMakeFiles/obj.clang-tblgen.dir/TableGen.cpp.o
> /Users/crazor/llvm/tools/clang/utils/TableGen/TableGen.cpp:244:37: error: too few arguments
>       to function call, at least argument 'Argv0' must be specified
>   sys::PrintStackTraceOnErrorSignal();
> 
> ``` ^
> /Users/crazor/llvm/include/llvm/Support/Signals.h:47:3: note: 'PrintStackTraceOnErrorSignal'
>       declared here
>   void PrintStackTraceOnErrorSignal(StringRef Argv0,
>   ^
> 1 error generated.
> make[2]: *** [tools/clang/utils/TableGen/CMakeFiles/obj.clang-tblgen.dir/TableGen.cpp.o] Error 1
> make[1]: *** [tools/clang/utils/TableGen/CMakeFiles/obj.clang-tblgen.dir/all] Error 2
> make: *** [all] Error 2
> 6,08s user 3,71s system 91% cpu 10,667s total
> ```

**Comment by Asher-** [comment]
Similar experience here. That error can be resolved by adding StringRef() as a single argument for the call to PrintStackTraceOnErrorSignal. 

Then an error occurs in tools/clang/lib/CodeGen/CGBuiltin.cpp for symbols r600_rsq and AMDGPU_ldexp. Commenting out the legacy AMD section resolves the error (but obviously isn't a general solution). 

Then an error occurs in tools/clang/lib/CodeGen/CGClass.cpp for llvm::Intrinsic::bitset_test, which does not appear to be defined anywhere. Presumably this is because of a version mismatch related to merging from upstream, as llvm/clang trunk compiles without problem but does not contain any reference to llvm::Intrinsic::bitset_test or the functions in CGClass.cpp that refer to llvm::Intrinsic::bitset_test. 

Not sure where to go from there.

**Comment by dylanmckay** [comment]
Should be able to be fixed by updating LLVM+clang, I'll do that tonight.

**Comment by RadhikaG** [comment]
Similar experience here as well. I came up with a few hacky solutions to try and get the build working, but was stumped at the llvm::Intrinsic part too.

**Comment by dylanmckay** [comment]
Updated LLVM and Clang, build went fine on my local machine :)

**Comment by Asher-** [comment]
New issues with Xcode 8.

See: https://github.com/avr-llvm/clang/issues/12

**Comment by Crazor** [comment]
Could build on 10.11.6 with Xcode 8 today.

Am Donnerstag, 15. September 2016 schrieb Asher :

**Comment by Asher-** [comment]
Any suggestions for what to try?

**Comment by Asher-** [comment]
For some reason, git pull for clang had not properly updated. Trying again now, I'm guessing it will work. Will report back.

**Comment by Asher-** [comment]
That was the problem. Success!

**Comment by RadhikaG** [comment]
@dylanmckay thank you very much!

After successfully completing at 100%, the build somehow generates an empty `clang-4.0` executable, and no `clang` executable at all in `llvm/build/bin`. Would any of you have an idea why? I'm on Linux, if that's any help.

**Comment by dylanmckay** [comment]
What happens when you delete the executable and run `make` again @RadhikaG?

**Comment by RadhikaG** [comment]
Worked like a charm, thanks!
